### ISSUE TITLE
CPU usage is a bit too high

### ISSUE THREAD

**Issue by monkey03297** [hoangcaominh/THLSC#2]
![image](https://user-images.githubusercontent.com/83492685/152803007-4c1e0d68-2d04-4d0d-ba39-dc0bfc1967b9.png)

**Comment by hoangcaominh** [comment]
I set the sleep time for the main thread to 1 millisecond, which leads to high CPU usage.
I can increase the thread's sleep time to reduce CPU usage in the next update.

**Comment by hoangcaominh** [comment]
Fixed in 03b0dfb1952e90bba78de47b7ec1d7d893f9e5e0
